name: Build and upload python package

on:
  # 手动触发
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # 只在推送版本标签时触发
    branches:
      - 'main'  # 或者在推送到 main 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install build twine
    
    - name: Set package version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          # 如果是 tag，提取版本号
          export VERSION="${GITHUB_REF#refs/tags/v}"
        else
          # 如果不是 tag，使用默认版本或从文件读取
          export VERSION=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml || echo "0.0.1")
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Building version: $VERSION"
        
        # 更新 pyproject.toml 中的版本号（如果需要）
        sed -i "s|version = \".*\"|version = \"${VERSION}\"|" pyproject.toml
    
    - name: Build package
      run: |
        python -m build
    
    - name: Publish to PyPI
      # 只在推送 tag 时发布到 PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*